name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHP Unit Report
      uses: php-actions/phpunit@v3
      with:
        version: 9.6.11
        php_extensions: gd xdebug
        coverage_clover: "coverage/clover.xml"
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      env:
        XDEBUG_MODE: coverage